version: '3.7'

services:
  frontend:
    container_name: frontend-dev
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules/'
    ports:
      - '3001:3000'
    depends_on:
      - api
  api:
    command: "flask run --host=0.0.0.0 --eager-loading --reload"
    depends_on:
      - elasticsearch
      - eshq
  eshq:
    image: elastichq/elasticsearch-hq
    ports:
    - 5001:5000
    depends_on:
    - elasticsearch
